# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements_tests.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements_tests.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements_tests.txt" }}

      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python -m pytest tests/

      - run:
          name: Running tests coverage and uploading results
          command: |
            . venv/bin/activate
            coverage run -m pytest
            coverage xml
            export CODACY_PROJECT_TOKEN=$CODACY_TOKEN
            python-codacy-coverage -r coverage.xml

      # tells CircleCI to allocate a new Docker Engine, separate from the environment that is running our job
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build and push Docker image
          command: |
            . venv/bin/activate
            docker build -t autodevops .
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PW
            docker tag autodevops $DOCKERHUB_USER/autodevops
            docker push $DOCKERHUB_USER/autodevops

      - run:
          name: Deploy app to VPS
          command: |
            #ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "/bin/bash deploy_app.sh"
            ssh $VPS_USER@$VPS_HOST 'bash -s' < deploy_app.sh $DOCKERHUB_USER $DOCKERHUB_PW

workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: master
